name: "Coverity"

on:
  workflow_dispatch

jobs:
  build:
    runs-on: Ubuntu-Latest
    container:
      image: fcbrbrazil/coverity:2022.6.0
      credentials:
        username: fcbrbrazil
        password: ${{ secrets.docker_hub_password}}
    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_SERVER_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_ACCESS_TOKEN }}
      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '14'

    - run: npm install

    # Perform Static Analysis
    - name: Polaris (SAST)
      run: |
        cov-build --dir idir --fs-capture-search . npm build .
        cov-analyze --dir idir --all --webapp-security --enable-audit-mode
